project:
  type: book
  
execute:
  freeze: true
  
book:
  title: "Estadística Espacial"
  author: 
  - name: "Luna Katerin Díaz Casallas"
    email: "ldiazca@unal.edu.co"
    affiliation: "Departamento de Estadística - Universidad Nacional de Colombia"
  - name: "Camilo Alejandro Raba Gómez"
    email: "craba@unal.edu.co"
    affiliation: "Departamento de Estadística - Universidad Nacional de Colombia"
  date: today
  page-navigation: true
  bread-crumbs: false
  sidebar:
    style: "floating"
    search: true
  chapters:
    - index.qmd
    - part: "Geoestadística"
      chapters:
        - Geo_uni.qmd
        - Geo_bi.qmd
    - part: "Geoestadística Espacio Temporal"
      chapters: 
        - Geo_esp_temp.qmd
    - part: "Geoestadística Funcional"
      chapters: 
        - Geo_fun.qmd
  #downloads: pdf
lang: es

format:
  html:
    toc: True
    toc-title: "Tabla de contenidos"
    toc-depth: 5  # Profundidad de los encabezados a enumerar
    number-sections: true  # Activa la numeración de secciones
    html-math-method: katex
    code-fold: true
    code-summary: "Ver código"
    code-block-bg: true
    code-block-border-left: "#2e66e4"
    link-external-newwindow: true
    css: styles.css
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    include-after-body: footer.html
    embed-resources: false
#  pdf:
#    documentclass: scrreprt
    
editor_options:
  chunk_output_type: console


